version: "3"

services:
  nginx:
    image: nginx
    restart: on-failure
    deploy:
      replicas: 4
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
  # opencv:
  #   build: ./TPDockerSampleApp
  #   deploy:
  #     replicas: 4
  #   expose:
  #     - 8080
  #   environment:
  #     - VIRTUAL_HOST=localhost
  #     - VIRTUAL_PORT=8080
  loadbalancer:
    image: jwilder/nginx-proxy
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

    
