
- name: enable microk8s DNS and storage
  command:
    cmd: microk8s enable dns storage

- name: enable microk8s dashboard and ingress
  command:
    cmd: microk8s enable dashboard ingress
- name: Enable microk8s registry
  command:
    cmd: microk8s enable registry